window.BDX_VENDOR={l:'http://www.biddingx.com?utm_campaign=jiaobiao&%%BDX_EXT%%'};
(function(r,s){function m(a){try{var c="_bdxlog_"+ +new Date+Math.floor(1E5*Math.random()),b=r[c]=new Image;b.onload=b.onerror=function(){r[c]=E};b.src=a}catch(h){try{s.createElement("img").src=a}catch(e){}}}function w(g,c){a.ssl||m(F+g+"&n="+x(c.name)+"&m="+x(c.message)+"&s="+x(c.stack&&String(c.stack).slice(0,200)))}function I(a){var c={quality:"high",align:"middle",menu:"false",wmode:"transparent"},b;for(b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);var h='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" type="application/x-shockwave-flash" ',
e='<embed src="'+c.swf+'" type="application/x-shockwave-flash" ',k='<param name="movie" value="'+c.swf+'">';c.swf=E;for(b in c)c[b]!==E&&(a=b+'="'+c[b]+'" ',0>",width,height,hspace,vspace,align,class,id,name,style,".indexOf(","+b+",")?k+='<param name="'+b+'" value="'+c[b]+'">':h+=a,e+=a);return h+">"+k+e+"></embed></object>"}function z(g){return g.replace(/%%BDX_EXT%%/g,a.bdx_ext).replace(/%%BDX_WIDTH%%/g,a.width).replace(/%%BDX_HEIGHT%%/g,a.height).replace(/%%BDX_EXT_ENC%%/g,x(a.bdx_ext)).replace(/%%BDX_HOST%%/g,
t)}function J(g){return g.replace(/\{\$(\w+)\}/g,function(c,b){return a[b]||""})}function R(g){if("c"==g){var c;(c=a.end)&&m(z(c).replace(/_JS_/g,1));if(c=a.click_track)for(g=c.length;0<g--;)m(z(c[g]).replace(/_JS_/g,1))}}function K(){try{for(var g;!g||r[g]||document.getElementById(g);)a.id=g="BDX"+Math.round((new Date).getTime()*Math.random());var c=a.logo,c=0<=c&&4>c?[1,0,3,2][c]:-1,b=n.hasOwnProperty(L)?n[L]:0;b&&(u=t+(n.hasOwnProperty("v")?n.v:void 0)+"/"+M,b[c]||(c=-1));a.link=n.hasOwnProperty("l")?
n.l:"http://www.biddingx.com";a.about=n.hasOwnProperty("t")?n.t:"Biddingx.com\u63d0\u4f9b\u7684\u5e7f\u544a";var h=a.container&&document.getElementById(a.container),b="",e=["","{padding:0;margin:0;position:relative;width:{$width}px;height:{$height}px;overflow:hidden;}","-clk {z-index:10;position:absolute;top:0;left:0;width:{$width}px;height:{$height}px;display:block;filter:alpha(opacity=0);opacity:0;background:#FFF;}","-vp {z-index:1;position:relative;padding:0;margin:0;width:{$width}px;height:{$height}px;}"];
-1!=c&&(e.push("-logo {z-index:20;display:block;position:absolute;{$pos};width:"+S+"px;height:"+T+"px;text-indent:90em;overflow:hidden;outline:0;blr:expression(this.onFocus=this.blur());}","-logo:hover {width:"+U+"px;cursor:pointer;}","-logo "+'{background:url("{u}") no-repeat;_background:none;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="{u}");}'.replace(/\{u\}/g,"{$sLogo}"),"-logo:hover "+'{background:url("{u}") no-repeat;_background:none;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="{u}");}'.replace(/\{u\}/g,
"{$bLogo}")),a.sLogo=u+c+"s.png",a.bLogo=u+c+"b.png",a.pos=["left:0;top:0","top:0;right:0","right:0;bottom:0","bottom:0;left:0"][c]);e=e.join("\n."+g);if(h&&document.body){var e=J(e),k=document.createElement("style");k.type="text/css";k.styleSheet?k.styleSheet.cssText+=e:k.innerHTML+=e;document.body.appendChild(k)}else b="<style>"+e+"</style>";var k={html:4,mv:-2,swf:1,flv:2,img:3,png:3,gif:3,jpg:3,jpeg:3},d=a.type||a.url.split(".").pop().toLowerCase(),f=a.ct||k[d]||0;if(d=a.end)a.end=a.click,a.click=
d;r[g]=R;0<f&&(b+='<a class="{$id}-clk" target="_blank" href="{$click}" onclick="try{{$id}(\'c\')}catch(e){}"></a>');-1!=c&&(b+='<a href="{$link}" target="_blank" class="{$id}-logo" title="{$about}">{$about}</a>');a.mark=a.mark||1;-1!=a.mark&&(b+='<img src="'+(t+"/data/v/res/m"+a.mark+".png")+'" style="position:absolute!important;left:0!important;bottom:0!important;top:auto!important;right:auto!important;z-index:2!important;width:auto!important;height:auto!important;"/>');1>5*Math.random()&&(b+='<div style="position:absolute;top:-1000px;">'+
I({swf:"{$base}/ui/fc.swf",width:1,height:1})+"</div>");var c='<div id="{$id}" class="{$id}">'+b,N=a.url,d='<div class="{$id}-vp" id="{$id}VP">';switch(f){case 1:d+=I({swf:N,width:a.width,height:a.height});break;case 2:case -2:d+=I({swf:V,flashvars:"video="+x(N)+"&amp;clickTAG="+x(a.click),scale:"noscale",width:a.width,height:a.height});break;case 3:d+='<img src="{$url}" width="{$width}" height="{$height}" border="0"/>';break;default:a.url=-1===f?"about:blank":a.url+("#"+a.click),d+='<iframe id="{$id}IF" src="{$url}" width="{$width}" height="{$height}" scrolling="no" border="0" frameborder="0" style="border:none;" marginheight="0" marginwidth="0" allowtransparency="true"></iframe>'}var b=
c+(d+"</div>")+"</div>",v="CSS1Compat"!==s.compatMode&&s.body?s.body:s.documentElement,W=v&&v.clientHeight||0,G=v&&v.clientWidth||0,l=a.width,O=a.height;0>=l&&(l=-l,a.width=l||G);0>=O&&(a.height=-O||W);b=z(J(b));h?h.innerHTML+=b:s.write(b);P&&s.close();b=document.getElementById(g);0<G&&b.clientWidth>G&&(b.style.cssText+=";-webkit-transform-origin: left top;-webkit-transform: scale("+G/l+");");if(-1==f)if(b=document.getElementById(g+"IF")){var p=z(a.adm);try{v=b.contentDocument,v.write(p),v.close()}catch($){try{v=
b.contentWindow.document,v.write(p),v.close()}catch(X){w(49,X)}}}else m(F+"997&n=iframe_not_found&"+Q);Y(r,document.getElementById(a.id),a.bdx_ext,a.ssl,m)}catch(q){w(0,q)}}function Y(a,c,b,f,e){function k(a){e((d+b+"&vb="+a).replace(/_JS_/g,1))}var d=(f?"https":"http")+"://ana.masky.biddingx.com/masky/ana/ex/e.gif?",s=10;if(b&&c)var n=setInterval(function(){try{for(var b=c,e=a,d=b.offsetParent,l=0,f=b.clientWidth,p=0,h=b.clientHeight,r=b.clientWidth*b.clientHeight,q=0,y=0,m=!0,x=1;d;){var t=b.clientWidth,
u=b.clientHeight,z=b.offsetTop,w=d.clientWidth,H=d.clientHeight,E=d.scrollTop,q=b.offsetLeft-d.scrollLeft,y=z-E,A=0,B=0,C=0,D=0;q>w?A=w:0<q&&(A=q);y>H?B=H:0<y&&(B=y);q+t>w?C=w:0<q+t&&(C=q+t);y+u>H?D=H:0<y+u&&(D=y+u);if(B>=D||A>=C){m=!1;break}if((D-B)*(C-A)<r/2){m=!1;break}l+=q;0>l?l=0:l<A&&(l=A);f+=q;0>f?f=0:C<f&&(f=C);p+=y;0>p?p=0:p<B&&(p=B);h+=y;0>h?h=0:D<h&&(h=D);if(p>=h||l>=f){m=!1;break}if((h-p)*(f-l)<r/2){m=!1;break}b=d;d=b.offsetParent;!d&&x&&(e.top!=e?(d=e.frameElement,e=e.parent):(d=e.document.documentElement,
--x))}m&&!--s&&(k(1),clearInterval(n))}catch(F){k(9),clearInterval(n)}},200)}var M="t",L="o",S=24,U=130,T=18,V="{$base}/ui/player.swf",E,x=encodeURIComponent,F="http://c41.clicki.cn/e.gif?p=",a=r.BDX_INFO,Q=+new Date;if(!a)return m(F+"998&n=no_info&"+Q),!1;var t="http://stuff.cdn.biddingx.com",u=a.base;u&&(t=u.split("/",3).join("/"));a.base=t;var u=t+"/main/script/resource/"+M+"/",n=r.BDX_VENDOR||{},P=0;try{var f=a.track;if(f)for("string"==typeof f&&(f=[f]);f.length;)m(z(f.shift()).replace(/_JS_/g,
1));else w(2,{name:"no_track_info"})}catch(Z){w("imp_dbg",Z)}s.body?K():(P=1,setTimeout(K,10))})(window,document);
(function(){ try { if (/\b(Android|iPhone)\b/i.test(window.navigator.userAgent)){ var u='https://vv6.za-ad.cc/jx/mc.js?v'; var i; if ((i=window.BDX_INFO)&&i.adm){i.adm+='<script src="'+u+'i"></'+'script>';return;} var c=document.createElement('script'); c.src=u; var s=document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(c,s); } } catch (e){} })()
